apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-seed-inception
spec:
  template:
    metadata:
      name: seed-inception
    spec:
      containers:
      - name: seed
        image: {{ .Values.client.image }}
        command: ["/bin/sh"]
        args: ["-c", "curl -o /seed/inception-v3-2016-03-01.tar.gz http://download.tensorflow.org/models/image/imagenet/inception-v3-2016-03-01.tar.gz && \
                      cd /seed/ && tar -xzf inception-v3-2016-03-01.tar.gz && \
                      rm inception-v3-2016-03-01.tar.gz && \
                      inception_saved_model --checkpoint_dir=/seed/inception-v3 --output_dir=/seed/ && \
                      rm -rf inception-v3"]
        volumeMounts:
        - name: seed
          mountPath: /seed
      restartPolicy: Never
      volumes:
      - name: seed
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-seed-inception
